### ISSUE TITLE
Unexpected/Unhandled TypeError

### ISSUE THREAD

**Issue by gjr80** [gjr80/weewx-realtime_gauge-data#30]
An unexpected restart lead to the following error:
```
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: processor: 3
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: model name: ARMv7 Processor rev 4 (v7l)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: BogoMIPS: 51.20
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: Features: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: CPU implementer: 0x41
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: CPU architecture: 7
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: CPU variant: 0x0
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: CPU part: 0xd03
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: CPU revision: 4
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: Hardware: BCM2835
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: Revision: a22082
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: Serial: 000000001d027eb8
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.cmon: cpuinfo: Model: Raspberry Pi 3 Model B Rev 1.2
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.engine: Archive will use data binding wx_binding
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.engine: Record generation will be attempted in 'hardware'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.engine: Using archive interval of 300 seconds (specified by hardware)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: WdArchive will use data binding wd_binding
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Using binding 'wd_binding' to database 'weewxwd'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Starting backfill of daily summaries
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.manager: Starting backfill of daily summaries
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.manager: Daily summaries up to date
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Daily summaries up to date.
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: WdSuppArchive will use data binding 'wdsupp_binding'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Using binding 'wdsupp_binding' to database 'wdsupp'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: max_age=691200 vacuum=86400
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Source 'WU' not enabled.
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Dark Sky API will be used for forecast and current conditions data
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.wd: Source 'File' not enabled.
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.restx: StationRegistry: Station will be registered.
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.restx: Wunderground-PWS: Data for station IQUEENSL336 will be posted
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.restx: PWSWeather: Data for station NARANGBAVP2 will be posted
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO weewx.engine: 'pyephem' detected, extended almanac data is available
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.low_battery: LowConsoleBattery alarm turned on. Voltage threshold 3.50, count threshold 5
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.rtgd: version is 0.6.0
Dec 13 00:01:47 cockatoo weewx-vantage[5737] INFO user.rtgd: RealTimeGaugeData scroller text will use Darksky forecast data
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__: Caught unrecoverable exception:
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****  float() argument must be a string or a number, not 'ValueTuple'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****  Traceback (most recent call last):
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 147, in main
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 93, in __init__
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****      self.loadServices(config_dict)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 161, in loadServices
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****    File "/home/weewx/bin/user/rtgd.py", line 1109, in __init__
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****      self.rtgd_thread = RealtimeGaugeDataThread(self.rtgd_ctl_queue,
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****    File "/home/weewx/bin/user/rtgd.py", line 1583, in __init__
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****      _vt = ValueTuple(float(_default[0]), self.units_dict[_group], _group)
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****  TypeError: float() argument must be a string or a number, not 'ValueTuple'
Dec 13 00:01:47 cockatoo weewx-vantage[5737] CRITICAL __main__:     ****  Exiting.
```

**Comment by AbelCT** [comment]
I have the same problem with Davis Vantage Pro2 cabled. The dataloger is serial version.
Almost every day at 00 hours the Weewx crash since the program and rtgd was updated to last version.
Weewx version is 4.9.1
```
Dec 31 23:50:41 server-home weewx-vantage[29113] INFO weewx.reportengine: Copied 2 files to /var/www/meteoberga
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: LOOP batch try #1; error: Expected to read 99 chars; got 0 instead
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: Unable to wake up Vantage console
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: LOOP batch try #2; error: Unable to wake up Vantage console
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: Unable to wake up Vantage console
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: LOOP batch try #3; error: Unable to wake up Vantage console
Jan  1 00:00:05 server-home weewx-vantage[29113] ERROR weewx.drivers.vantage: LOOP max batch errors (3) exceeded.
Jan  1 00:00:05 server-home weewx-vantage[29113] INFO weewx.engine: Main loop exiting. Shutting engine down.
Jan  1 00:00:05 server-home weewx-vantage[29113] INFO weewx.engine: Shutting down StdReport thread
Jan  1 00:00:05 server-home weewx-vantage[29113] CRITICAL __main__: Caught WeeWxIOError: LOOP max batch errors (3) exceeded.
Jan  1 00:00:05 server-home weewx-vantage[29113] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...
Jan  1 00:01:05 server-home weewx-vantage[29113] INFO __main__: retrying...
Jan  1 00:01:05 server-home weewx-vantage[29113] INFO weewx.engine: Loading station type Vantage (weewx.drivers.vantage)
Jan  1 00:01:05 server-home weewx-vantage[29113] INFO weewx.engine: StdConvert target unit is 0x11
Jan  1 00:01:05 server-home weewx-vantage[29113] INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.engine: Archive will use data binding wx_binding
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.engine: Record generation will be attempted in 'hardware'
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.engine: Using archive interval of 600 seconds (specified by hardware)
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: StationRegistry: Station will be registered.
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: Wunderground-PWS: Data for station IBACELON1 will be posted
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: PWSWeather: Data for station CW7218 will be posted
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: CWOP: Data for station CW7218 will be posted
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: WOW: Posting not enabled.
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.restx: AWEKAS: Data will be uploaded for user AcT2005
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: service version is 0.24
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: binding to ['archive', 'loop']
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: data_binding is wx_binding
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: topic is weather
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: desired unit system is METRICWX
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.mqtt: data will be uploaded to mqtt://***:***@localhost:1883/
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.wcloud: service version is 0.13
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.wcloud: Data will be uploaded for id=******
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO weewx.engine: 'pyephem' detected, extended almanac data is available
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.rtgd: version is 0.6.1
Jan  1 00:01:06 server-home weewx-vantage[29113] INFO user.rtgd: RealTimeGaugeData scroller text will use Weather Underground forecast data
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__: Caught unrecoverable exception:
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****  float() argument must be a string or a number, not 'ValueTuple'
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****  Traceback (most recent call last):
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 148, in main
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 93, in __init__
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****      self.loadServices(config_dict)
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 161, in loadServices
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****    File "/home/weewx/bin/user/rtgd.py", line 768, in __init__
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****      altitude=convert(engine.stn_info.altitude_vt, 'meter').value)
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****    File "/home/weewx/bin/user/rtgd.py", line 1236, in __init__
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****      _vt = ValueTuple(float(_default[0]), self.units_dict[_group], _group)
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****  TypeError: float() argument must be a string or a number, not 'ValueTuple'
Jan  1 00:01:06 server-home weewx-vantage[29113] CRITICAL __main__:     ****  Exiting.

```

**Comment by gjr80** [comment]
@AbelCT . I think I have this problem fixed. If you want to give it a try before I release v0.6.2 you can install `rtgd.py` v0.6.2b1 as follows:

1. move your current `/home/weewx/bin/user/rtgd.py` aside by renaming it, say to `rtgd_0_6_1.py`
2. download v0.6.2b1:
`$ wget -P /home/weewx/bin/user https://raw.githubusercontent.com/gjr80/weewx-realtime_gauge-data/issue_30/bin/user/rtgd.py`
3. restart WeeWX

Of course any recoverable errors that cause the WeeWX engine to restart will still occur, but rtgd should no longer cause a fatal error during such restarts. Please let me know if any issues.

**Comment by AbelCT** [comment]
Thanks. I installed this new version. At the moment the Weewx has started well.

**Comment by gjr80** [comment]
Closing as no more errors have been reported and v0.6.2 has been released
