### ISSUE TITLE
Possible issue with today's max gust during first archive period after midnight

### ISSUE THREAD

**Issue by gjr80** [gjr80/weewx-realtime_gauge-data#4]
The following log excerpt may be symptomatic of an issue since fixed (it didn't happen just after midnight on 26 Feb) but it needs to be checked:
```
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: **** Traceback (most recent call last):
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 835, in process_packet
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: ****     data = self.calculate(cached_packet)
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: ****   File "/home/weewx/bin/user/rtgd.py", line 1305, in calculate
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: ****     data['wgustTM'] = self.wind_format % wgustTM
Feb 25 00:00:29 stormbird weewx[16139]: rtgdthread: **** TypeError: float argument required, not NoneType
```

**Comment by gjr80** [comment]
Error has no re-appeared, suspect it was in fact fixed.
